name: image-sync
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 15 * * *"

env:
  IMAGE_SYNCER_VERSION: v1.3.1
  DOCKER_NAMESPACE: $GITHUB_REPOSITORY_OWNER
  DOCKER_REGISTRY: "registry.hub.docker.com"
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install image-sync tool
        run: |
          wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
          tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz

      - name: add sercret to file
        run: envsubst < auth.json > auth.bak.json

      - name: sync images
        run: ./image-syncer --proc=10 --auth=./auth.bak.json --images=./images.json --namespace=${DOCKER_NAMESPACE} --registry=${DOCKER_REGISTRY} --retries=3
